import { useState } from "react"
const TEAL="#0d4f5c";const TEAL2="#0a7a8c";const TEAL3="#14b8a6";const TEAL4="#2dd4bf";const BG="#050f14";const BG2="#0a1a1f";const BG3="#0d2530";const GD="#fbbf24";const GD2="#f59e0b";const W="#ffffff";const GY="#7dd3e0";const GY2="#5bb8cc"
const files=[{n:"01_Quickstart_Guide.md",s:"5.1 KB",d:"Hook system overview, script structure, and 20-minute setup plan"},{n:"02_The_Hook_System.md",s:"14.2 KB",d:"10 proven hook structures with examples, use cases, and platform selection guide"},{n:"03_30_Script_Templates.md",s:"38.9 KB",d:"30 ready-to-film scripts: educational, proof, relatable, sales, storytelling"},{n:"04_BRoll_Insertion_Guide.md",s:"11.8 KB",d:"B-roll placement rules, 7 cut points, scene sheet template"},{n:"05_AI_Dialogue_Generator.md",s:"14.6 KB",d:"8 AI prompts to generate full scripts in 90 seconds"}]
const hooks=[{n:"01",t:"Question",d:"Create curiosity with a question the viewer needs answered"},{n:"02",t:"Statement",d:"Bold declarative claim that creates mental resistance"},{n:"03",t:"Number",d:"Specificity of a list or framework attracts attention"},{n:"04",t:"Contrast",d:"Pattern interrupt between two opposing ideas"},{n:"05",t:"Scene",d:"Real-time experience creates authenticity and immediacy"},{n:"06",t:"Proof",d:"Specific result creates credibility and aspiration"}]
const feat=[{i:"HOOKS",t:"10 Hook Structures",d:"10 proven patterns that stop scrolling. Question, statement, number, contrast, scene, proof, threat, insider, relatable, and stat hooks."},{i:"SCRIPTS",t:"30 Script Templates",d:"30 ready-to-film scripts. Educational, proof, relatable, sales, storytelling, and platform-specific formats. Copy and customize."},{i:"B-ROLL",t:"B-Roll Insertion Guide",d:"7 placement rules. When to cut, where to cut, and what to show. Every cut is intentional."},{i:"AI",t:"8 AI Script Prompts",d:"Generate full scripts from a topic in 90 seconds. One for every content format you need."},{i:"PLATFORM",t:"Platform-Specific Scripts",d:"TikTok, Reels, YouTube Shorts, and long-form YouTube. Each optimized for the platform algorithm."},{i:"BATCH",t:"Weekly Content Batching",d:"Prompt to generate 7 scripts for the week with different hook angles and formats."}]
const starter=["Quickstart Guide + Hook System Overview","10 Hook Structure Templates","5 Full Script Templates (from 30)","B-Roll Insertion Guide","48-hour email support"]
const complete=["Everything in Starter","All 30 Script Templates (full collection)","8 AI Dialogue Generator Prompts","B-Roll Scene Sheet Template","Priority 24h support"]
const faqs=[{q:"Do I need to be on camera?",a:"No. These scripts work for voice-over, screen recording, talking head, and B-roll only formats. Each template includes B-roll cues so you can film with or without your face."},{q:"How fast can I generate a script?",a:"The AI Dialogue Generator produces a full 60-second script in 60-90 seconds. The 30 template scripts are ready to film immediately  just customize the brackets."},{q:"Do these work for all platforms?",a:"Yes. Scripts are optimized for TikTok, Instagram Reels, YouTube Shorts, and long-form YouTube. Platform-specific templates are included."},{q:"What is B-roll?",a:"B-roll is the supplementary footage that plays over your voice or alongside your talking head. The guide teaches you exactly when and where to insert it for maximum effect."},{q:"How many scripts are in this kit?",a:"35 total. 30 ready-to-film templates plus 8 AI prompts that generate unlimited custom scripts. Each template covers a distinct format and angle."},{q:"Is there a refund?",a:"Digital products are non-refundable once downloaded. If files are corrupted, contact us and we will resolve it immediately."}]
const stats=[{s:"10",l:"Proven hook structures"},{s:"30",l:"Ready-to-film script templates"},{s:"90sec",l:"AI script generation time"},{s:"8",l:"AI prompt templates"}]
export default function App(){const[o,setO]=useState<number|null>(null);return(
React.createElement("div",{style:{background:BG,color:W,fontFamily:"Georgia,serif",minHeight:"100vh"}},
React.createElement("nav",{style:{background:"rgba(5,15,20,0.95)",backdropFilter:"blur(12px)",borderBottom:"1px solid rgba(251,191,36,0.1)",position:"sticky",top:0,zIndex:100}},
React.createElement("div",{style:{maxWidth:1100,margin:"0 auto",padding:"14px 24px",display:"flex",justifyContent:"space-between",alignItems:"center"}},
React.createElement("div",{style:{display:"flex",alignItems:"center",gap:10}},
React.createElement("div",{style:{width:34,height:34,borderRadius:8,background:"linear-gradient(135deg,#0a7a8c,#fbbf24)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,fontWeight:900,color:W}},"V"),
React.createElement("span",{style:{fontWeight:700,fontSize:18}},"Viral Video Script System ",React.createElement("span",{style:{color:GD}},"AI"))),
React.createElement("div",{style:{display:"flex",gap:32,alignItems:"center"}},
[["Inside","inside"],["Hooks","hooks"],["Pricing","pricing"],["FAQ","faq"]].map(([l,id])=>React.createElement("a",{key:l,href:"#"+id,style:{color:GY,textDecoration:"none",fontSize:14,fontFamily:"system-ui,sans-serif"}},l)),
React.createElement("a",{href:"#pricing",style:{background:GD,color:"#050f14",padding:"8px 20px",borderRadius:8,textDecoration:"none",fontWeight:700,fontSize:14,fontFamily:"system-ui,sans-serif"}},"Get the Kit"))))),
React.createElement("section",{style:{maxWidth:1100,margin:"0 auto",padding:"80px 24px 60px",display:"grid",gridTemplateColumns:"1fr 1fr",gap:60,alignItems:"center"}},
React.createElement("div",null,
React.createElement("div",{style:{display:"inline-flex",alignItems:"center",gap:8,backgroundColor:"rgba(251,191,36,0.08)",border:"1px solid rgba(251,191,36,0.2)",borderRadius:100,padding:"6px 14px",marginBottom:24}},
React.createElement("span",{style:{fontSize:14,color:GD,fontWeight:600,fontFamily:"system-ui,sans-serif"}},"VHS 10 Hooks. 30 Scripts. 90 Seconds.")),
React.createElement("h1",{style:{fontSize:48,fontWeight:900,lineHeight:1.1,letterSpacing:"-1.5px",marginBottom:20}},"Write Videos That ",React.createElement("br",null),React.createElement("span",{style:{color:GD}},"Stop the Scroll.")),
React.createElement("p",{style:{fontSize:19,color:GY,lineHeight:1.7,marginBottom:12,fontFamily:"system-ui,sans-serif"}},"10 proven hook structures. 30 ready-to-film scripts. 8 AI prompts that generate full scripts in 90 seconds. A repeatable production system for every platform."),
React.createElement("p",{style:{fontSize:14,color:GY2,marginBottom:36,fontFamily:"system-ui,sans-serif"}},"For video creators who are done staring at a blank page."),
React.createElement("a",{href:"#pricing",style:{background:GD,color:"#050f14",padding:"14px 32px",borderRadius:10,textDecoration:"none",fontWeight:800,fontSize:16,display:"inline-block",boxShadow:"0 4px 20px rgba(251,191,36,0.25)"}},"Get Instant Access  From $27"),
React.createElement("div",{style:{display:"flex",gap:24,marginTop:24,flexWrap:"wrap"}},
["10 hook structures","30 script templates","B-roll insertion guide","8 AI script prompts","Platform-optimized"].map(b=>React.createElement("div",{key:b,style:{display:"flex",alignItems:"center",gap:6}},React.createElement("span",{style:{color:GD,fontSize:13}},""),React.createElement("span",{style:{color:GY,fontSize:13,fontFamily:"system-ui,sans-serif"}},b)))))),
React.createElement("div",{style:{backgroundColor:BG2,borderRadius:20,padding:28,border:"1px solid rgba(20,184,166,0.2)",boxShadow:"0 8px 40px rgba(20,184,166,0.06)"}},
React.createElement("div",{style:{marginBottom:16,fontSize:13,color:TEAL3,fontWeight:700,fontFamily:"system-ui,sans-serif",letterSpacing:"0.5px"}},"THE SCRIPT PRODUCTION SYSTEM"),
[{n:"1",t:"Hook",d:"3 seconds. Pick a hook structure. Write the one sentence that stops scrolling."},{n:"2",t:"Template",d:"Choose a script format. Educational, proof, relatable, sales, or storytelling."},{n:"3",t:"Fill",d:"Customize the brackets. Your details go in. The structure is already done."},{n:"4",t:"Film",d:"B-roll cues tell you exactly when and where to cut. Every cut is intentional."},{n:"5",t:"AI Generate",d:"Run your topic through the AI Dialogue Generator. Full script in 90 seconds."}].map(p=>React.createElement("div",{key:p.n,style:{display:"flex",gap:12,marginBottom:10}},
React.createElement("div",{style:{width:32,height:32,borderRadius:8,backgroundColor:TEAL2,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:800,fontSize:11,color:W,flexShrink:0,fontFamily:"system-ui,sans-serif"}},p.n),
React.createElement("div",{style:{flex:1,paddingBottom:10}},
React.createElement("div",{style:{fontSize:13,fontWeight:700,marginBottom:2,color:W,fontFamily:"system-ui,sans-serif"}},p.t),
React.createElement("div",{style:{fontSize:12,color:GY,lineHeight:1.5,fontFamily:"system-ui,sans-serif"}},p.d)))),
React.createElement("div",{style:{marginTop:14,backgroundColor:"rgba(20,184,166,0.08)",borderRadius:8,padding:"10px 14px",border:"1px solid rgba(20,184,166,0.2)"}},
React.createElement("div",{style:{fontSize:12,color:TEAL3,fontWeight:600,fontFamily:"system-ui,sans-serif"}},"Result: Complete 60-second script in 20 minutes"),
React.createElement("div",{style:{fontSize:12,color:GY2,fontFamily:"system-ui,sans-serif",marginTop:2}},"Hook + template + fill + film + post. Repeatable.")))),
React.createElement("section",{style:{borderTop:"1px solid rgba(251,191,36,0.06)",borderBottom:"1px solid rgba(251,191,36,0.06)",backgroundColor:BG2}},
React.createElement("div",{style:{maxWidth:1100,margin:"0 auto",padding:"20px 24px",display:"flex",justifyContent:"space-around",flexWrap:"wrap",gap:16}},
stats.map(i=>React.createElement("div",{key:i.l,style:{textAlign:"center"}},
React.createElement("div",{style:{fontSize:28,fontWeight:900,color:GD,fontFamily:"system-ui,sans-serif"}},i.s),
React.createElement("div",{style:{fontSize:12,color:GY,marginTop:4,fontFamily:"system-ui,sans-serif"}},i.l))))),
React.createElement("section",{id:"inside",style:{backgroundColor:BG2}},
React.createElement("div",{style:{maxWidth:1100,margin:"0 auto",padding:"80px 24px"}},
React.createElement("div",{style:{textAlign:"center",marginBottom:56}},
React.createElement("h2",{style:{fontSize:40,fontWeight:900,marginBottom:16,letterSpacing:"-1px"}},"5 Files. 10 Hooks. 30 Scripts."),
React.createElement("p",{style:{color:GY,fontSize:18,fontFamily:"system-ui,sans-serif"}},"Everything you need to go from blank page to filmed script in under 30 minutes.")),
React.createElement("div",{style:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:48}},
React.createElement("div",null,files.map((f,i)=>React.createElement("div",{key:f.n,style:{backgroundColor:BG,borderRadius:12,padding:20,marginBottom:12,border:"1px solid rgba(20,184,166,0.08)",display:"flex",gap:16,alignItems:"flex-start"}},
React.createElement("div",{style:{width:40,height:40,borderRadius:8,backgroundColor:"rgba(20,184,166,0.1)",border:"1px solid rgba(20,184,166,0.2)",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,color:GD,fontSize:14,flexShrink:0,fontFamily:"system-ui,sans-serif"}},String(i+1).padStart(2,"0")),
React.createElement("div",null,
React.createElement("div",{style:{fontWeight:700,fontSize:14,marginBottom:4,fontFamily:"system-ui,sans-serif",color:W}},f.n),
React.createElement("div",{style:{color:GY,fontSize:12,marginBottom:4,fontFamily:"system-ui,sans-serif"}},f.d),
React.createElement("div",{style:{color:GD,fontSize:11,fontFamily:"system-ui,sans-serif"}},f.s)))))),
React.createElement("div",null,
React.createElement("div",{style:{background:"linear-gradient(135deg,#0a1a1f,#0d2530)",borderRadius:16,padding:32,border:"1px solid rgba(20,184,166,0.25)",marginBottom:24}},
React.createElement("div",{style:{fontSize:13,color:TEAL3,fontWeight:700,marginBottom:12,fontFamily:"system-ui,sans-serif",letterSpacing:"0.5px",textTransform:"uppercase"}},"The Transformation"),
React.createElement("h3",{style:{fontSize:24,fontWeight:900,marginBottom:16,color:GY}},"Old: Staring at a blank page"),
React.createElement("p",{style:{color:GY2,fontSize:15,lineHeight:1.7,marginBottom:16,fontFamily:"system-ui,sans-serif"}},"You spend 45 minutes trying to figure out what to say. You record, you delete, you record again. The script never feels right. You post inconsistently because writing takes too long."),
React.createElement("div",{style:{display:"flex",alignItems:"center",gap:10,marginBottom:16}},
React.createElement("div",{style:{flex:1,height:1,backgroundColor:"rgba(20,184,166,0.3)"}}),
React.createElement("span",{style:{color:GD,fontSize:18}},"->"),
React.createElement("div",{style:{flex:1,height:1,backgroundColor:"rgba(20,184,166,0.3)"}})),
React.createElement("h3",{style:{fontSize:24,fontWeight:900,color:TEAL3}},"New: Open template, fill brackets, film"),
React.createElement("p",{style:{color:GY2,fontSize:15,lineHeight:1.7,fontFamily:"system-ui,sans-serif"}},"Pick a hook. Choose a template. Fill in your details. The B-roll cues tell you where to cut. You have a complete, filmed script in 30 minutes. Repeatable every day."))),
React.createElement("div",{style:{backgroundColor:BG,borderRadius:12,padding:20,border:"1px solid rgba(20,184,166,0.1)"}},
React.createElement("div",{style:{fontSize:13,color:TEAL3,fontWeight:700,marginBottom:12,fontFamily:"system-ui,sans-serif"}},"THE HOOK TO FILM PIPELINE"),
React.createElement("p",{style:{color:GY,fontSize:14,lineHeight:1.7,fontFamily:"system-ui,sans-serif"}},"Hook (3 sec) -> Template (fill brackets) -> B-roll cues (where to cut) -> AI generation (90 sec backup) -> Film -> Post. That is the entire system. Repeatable. Every day."))))))),
React.createElement("section",{id:"hooks",style:{maxWidth:900,margin:"0 auto",padding:"80px 24px",textAlign:"center"}},
React.createElement("h2",{style:{fontSize:40,fontWeight:900,marginBottom:16,letterSpacing:"-1px"}},"The 10 Hook Structures"),
React.createElement("p",{style:{color:GY,fontSize:18,marginBottom:56,fontFamily:"system-ui,sans-serif"}},"Every one of these stops the scroll. Pick one. Write the sentence. Everything else supports it."),
React.createElement("div",{style:{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:16}},
hooks.map(s=>React.createElement("div",{key:s.n,style:{backgroundColor:BG2,borderRadius:16,padding:24,border:"1px solid rgba(20,184,166,0.1)",textAlign:"center"}},
React.createElement("div",{style:{width:40,height:40,borderRadius:"50%",backgroundColor:TEAL2,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,fontSize:16,color:W,margin:"0 auto 12px",fontFamily:"system-ui,sans-serif"}},s.n),
React.createElement("h3",{style:{fontSize:16,fontWeight:800,marginBottom:8,fontFamily:"system-ui,sans-serif",color:TEAL3}},s.t),
React.createElement("p",{style:{color:GY,fontSize:12,lineHeight:1.6,fontFamily:"system-ui,sans-serif"}},s.d)))),
React.createElement("p",{style:{color:GY2,fontSize:13,marginTop:20,fontFamily:"system-ui,sans-serif"}},"+ 4 more hook structures in the kit")),
React.createElement("section",{style:{backgroundColor:BG2,borderTop:"1px solid rgba(251,191,36,0.06)"}},
React.createElement("div",{style:{maxWidth:1100,margin:"0 auto",padding:"80px 24px"}},
React.createElement("div",{style:{textAlign:"center",marginBottom:56}},
React.createElement("h2",{style:{fontSize:40,fontWeight:900,letterSpacing:"-1px",marginBottom:16}},"What the Kit Gives You"),
React.createElement("p",{style:{color:GY,fontSize:18,fontFamily:"system-ui,sans-serif"}},"Six tools. One repeatable system. Every video you make, covered.")),
React.createElement("div",{style:{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:20}},
...feat.map(f=>React.createElement("div",{key:f.t,style:{backgroundColor:BG,borderRadius:14,padding:24,border:"1px solid rgba(20,184,166,0.1)"}},
React.createElement("div",{style:{fontSize:11,color:GD,fontWeight:700,marginBottom:8,fontFamily:"system-ui,sans-serif",letterSpacing:"1px"}},f.i),
React.createElement("h3",{style:{fontWeight:800,fontSize:15,marginBottom:8,color:W}},f.t),
React.createElement("p",{style:{color:GY,fontSize:13,lineHeight:1.6}},f.d))))),
React.createElement("section",{id:"pricing",style:{maxWidth:900,margin:"0 auto",padding:"80px 24px"}},
React.createElement("div",{style:{textAlign:"center",marginBottom:56}},
React.createElement("h2",{style:{fontSize:44,fontWeight:900,letterSpacing:"-1.5px",marginBottom:16}},"One System. Two Tiers."),
React.createElement("p",{style:{color:GY,fontSize:18,fontFamily:"system-ui,sans-serif"}},"Write your first script in 20 minutes. Build a content system in a week.")),
React.createElement("div",{style:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:24,maxWidth:800,margin:"0 auto"}},
React.createElement("div",{style:{backgroundColor:BG2,borderRadius:20,padding:36,border:"1px solid rgba(20,184,166,0.15)"}},
React.createElement("div",{style:{fontSize:13,color:GY,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.5px",marginBottom:12,fontFamily:"system-ui,sans-serif"}},"Starter"),
React.createElement("div",{style:{display:"flex",alignItems:"baseline",gap:8,marginBottom:20}},
React.createElement("span",{style:{fontSize:52,fontWeight:900}},""),
React.createElement("span",{style:{color:GY,fontSize:15}},"one-time")),
React.createElement("p",{style:{color:GY,fontSize:14,marginBottom:28,lineHeight:1.6,fontFamily:"system-ui,sans-serif"}},"The complete script system. 10 hooks, 5 templates, B-roll guide, and the AI prompt system."),
React.createElement("ul",{style:{listStyle:"none",padding:0,marginBottom:32}},starter.map(item=>React.createElement("li",{key:item,style:{display:"flex",gap:10,marginBottom:12,fontSize:14,alignItems:"flex-start"}},
React.createElement("span",{style:{color:GD,flexShrink:0,fontWeight:700}},""),
React.createElement("span",{style:{color:W}},item)))),
React.createElement("a",{href:"#",style:{display:"block",textAlign:"center",backgroundColor:"rgba(251,191,36,0.08)",color:GD,padding:"14px",borderRadius:10,textDecoration:"none",fontWeight:700,fontSize:15,border:"1px solid rgba(251,191,36,0.2)",fontFamily:"system-ui,sans-serif"}},"Get the Script Kit")),
React.createElement("div",{style:{backgroundColor:"rgba(251,191,36,0.05)",borderRadius:20,padding:36,border:"2px solid rgba(251,191,36,0.35)",position:"relative",boxShadow:"0 8px 40px rgba(20,184,166,0.08)"}},
React.createElement("div",{style:{position:"absolute",top:-14,left:24,backgroundColor:GD,color:"#050f14",padding:"4px 14px",borderRadius:100,fontWeight:800,fontSize:12,fontFamily:"system-ui,sans-serif"}},"FULL SYSTEM"),
React.createElement("div",{style:{fontSize:13,color:GD,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.5px",marginBottom:12,fontFamily:"system-ui,sans-serif"}},"Complete"),
React.createElement("div",{style:{display:"flex",alignItems:"baseline",gap:8,marginBottom:20}},
React.createElement("span",{style:{fontSize:52,fontWeight:900,color:W}},""),
React.createElement("span",{style:{color:GY2,fontSize:15}},"one-time")),
React.createElement("p",{style:{color:GY2,fontSize:14,marginBottom:28,lineHeight:1.6,fontFamily:"system-ui,sans-serif"}},"Starter plus all 30 script templates and the complete AI Dialogue Generator collection."),
React.createElement("ul",{style:{listStyle:"none",padding:0,marginBottom:32}},complete.map(item=>React.createElement("li",{key:item,style:{display:"flex",gap:10,marginBottom:12,fontSize:14,alignItems:"flex-start"}},
React.createElement("span",{style:{color:GD,flexShrink:0,fontWeight:700}},""),
React.createElement("span",{style:{color:W}},item)))),
React.createElement("a",{href:"#",style:{display:"block",textAlign:"center",backgroundColor:GD,color:"#050f14",padding:"14px",borderRadius:10,textDecoration:"none",fontWeight:700,fontSize:15,fontFamily:"system-ui,sans-serif"}},"Get the Complete System")))),
React.createElement("p",{style:{textAlign:"center",color:GY,fontSize:13,marginTop:24,fontFamily:"system-ui,sans-serif"}},"Instant download. Files are yours to keep. No subscriptions.")),
React.createElement("section",{id:"faq",style:{maxWidth:800,margin:"0 auto",padding:"0 24px 80px"}},
React.createElement("div",{style:{textAlign:"center",marginBottom:48}},
React.createElement("h2",{style:{fontSize:40,fontWeight:900}},"Questions. Answered.")),
React.createElement("div",null,faqs.map((faq,i)=>React.createElement("div",{key:i,style:{borderBottom:"1px solid rgba(20,184,166,0.08)"}},
React.createElement("button",{onClick:()=>setO(o===i?null:i),style:{width:"100%",background:"none",border:"none",color:W,padding:"20px 0",display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer",fontSize:16,fontWeight:600,textAlign:"left",gap:16,fontFamily:"system-ui,sans-serif"}},
faq.q,React.createElement("span",{style:{color:GD,fontSize:20,flexShrink:0}},o===i?"":"+")),
o===i&&React.createElement("div",{style:{paddingBottom:20,color:GY,fontSize:15,lineHeight:1.7,fontFamily:"system-ui,sans-serif"}},faq.a))))),
React.createElement("section",{style:{background:"linear-gradient(135deg,#050f14,#0a1a1f)",borderTop:"1px solid rgba(251,191,36,0.06)",textAlign:"center",padding:"80px 24px"}},
React.createElement("div",{style:{maxWidth:600,margin:"0 auto"}},
React.createElement("div",{style:{fontSize:48,marginBottom:20}},"V"),
React.createElement("h2",{style:{fontSize:40,fontWeight:900,marginBottom:16,letterSpacing:"-1px",color:W}},"Your Next Video Is ",React.createElement("br",null),"Already Written."),
React.createElement("p",{style:{color:GY,fontSize:18,lineHeight:1.6,marginBottom:40,fontFamily:"system-ui,sans-serif"}},"10 hooks. 30 templates. 8 AI prompts. A complete system for writing, filming, and posting videos on repeat."),
React.createElement("a",{href:"#pricing",style:{backgroundColor:GD,color:"#050f14",padding:"16px 40px",borderRadius:12,textDecoration:"none",fontWeight:900,fontSize:18,display:"inline-block",fontFamily:"system-ui,sans-serif",boxShadow:"0 4px 30px rgba(251,191,36,0.3)"}},"Get Instant Access  From "),
React.createElement("p",{style:{color:GY2,fontSize:13,marginTop:16}},"One-time purchase. Instant download. No subscriptions."))),
React.createElement("footer",{style:{borderTop:"1px solid rgba(251,191,36,0.05)",padding:"24px",textAlign:"center",color:GY,fontSize:12,fontFamily:"system-ui,sans-serif"}},
React.createElement("div",{style:{maxWidth:1100,margin:"0 auto"}},
React.createElement("p",null,"2026 AI Microtec. Personal use only. Not for resale."),
React.createElement("p",{style:{marginTop:8}},"Viral Video Script System  10 Hooks. 30 Scripts. 90 Seconds.")))))
)}